name: push
on:
  push:
  pull_request:
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        os-name: [Ubuntu]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        # we do not want a large number of windows and macos builds, so
        # enumerate them explicitly
        include:
          - os: windows-latest
            os-name: Windows
            python-version: 3.9
          - os: macos-latest
            os-name: MacOS
            python-version: 3.9
          - os: ubuntu-20.04
            os-name: Ubuntu 20.04
            python-version: 3.6
    name: "Test py${{ matrix.python-version }} on ${{ matrix.os-name }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install -U pip setuptools tox
      - run: python -m tox -e py

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - run: python -m pip install -U pip setuptools tox
      - run: python -m tox -e mypy

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - run: python -m pip install -U pip setuptools tox
      - run: python -m tox -e flake8,isort,black

  test-doc-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - run: python -m pip install -U pip setuptools tox
      - run: python -m tox -e docs
