name: Enforce Changelog Fragment
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - opened
      - reopened
      - synchronize

jobs:
  call-scriv-workflow:
    uses: globus/globus-sdk-python/.github/workflows/has_changelog.yaml@main
